spring.application.name=auth-service
spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

spring.datasource.url=jdbc:postgresql://${AUTH_HOST}:${AUTH_PORT}/${AUTH_DB}?TimeZone=America/Sao_Paulo
spring.datasource.username=${AUTH_USER}
spring.datasource.password=${AUTH_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
security.jwt.secret-key=QGXgm8syhGOcl8UlHI8l4wAAx/+ztNB3ZDULgAO64X4=
security.jwt.expiration-time=3600000
spring.jpa.hibernate.ddl-auto=validate