spring.application.name=notification-service
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/notifications?authSource=admin

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest


security.jwt.secret-key=${JWT_SECRET}


server.port=8084