events {
  worker_connections 1024;
}

http {
  server {
    listen 80;

    location /api/auth/ {
      proxy_pass http://auth-service:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    location /api/users/ {
      proxy_pass http://user-service:8081;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    location /api/users/me/avatar {
      proxy_pass http://user-service:8081;
      client_max_body_size 10M;
      proxy_set_header Host $host;
    }


    location /api/workspaces/ {
      proxy_pass http://workspace-service:8082;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /tasks/api/ {
      proxy_pass http://task-service:8083;
    }

  }
}