package com.mobflow.notificationservice.model.enums;

public enum NotificationType {
    EMAIL_CONFIRMATION,
    TASK_CREATED,
    TASK_ASSIGNED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_COMPLETED,
    TASK_DUE_SOON,
    WORKSPACE_INVITE,
    WORKSPACE_INVITE_ACCEPTED,
    WORKSPACE_MEMBER_ADDED,
    WORKSPACE_MEMBER_REMOVED,
    WORKSPACE_ROLE_CHANGED
}
